<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="_Oving5.ipynb">Øving 5</a>
    </div>
    <ul class="nav navbar-nav">
      <li ><a href="Generelt%20om%20lister.ipynb">Generelt om lister</a></li>
    <li ><a href="Lett%20og%20blandet.ipynb">Lett og blandet</a></li>
    <li ><a href="Intro%20til%20numpy-arrays.ipynb">Intro til numpy-arrays</a></li>
    <li ><a href="Kodeforstaelse.ipynb">Kodeforståelse</a></li>
    <li ><a href="Vektorer.ipynb">Vektorer</a></li>
    <li ><a href="Lister%20og%20lokker.ipynb">Lister og løkker</a></li>
    <li ><a href="Teoridelen%20paa%20eksamen.ipynb">Teoridelen på eksamen</a></li>
    <li ><a href="Gangetabell%20og%20lister.ipynb">Gangetabell og lister</a></li>
    <li ><a href="Lotto.ipynb">Lotto</a></li>
    <li ><a href="Tannfeen.ipynb">Tannfeen</a></li>
        <li class="active"><a href="Chattebot.ipynb">Chattebot</a></li>
    <li ><a href="Matriseaddisjon.ipynb">Matriseaddisjon</a></li>
    </ul>
  </div>
</nav>

# Matriseaddisjon

**Læringsmål:**

* Lister av flere dimensjoner


I denne oppgaven skal du implementere noen funksjoner slik at to matriser blir skrevet ut på et fint format og addert med hverandre. 

En matrise er et godt eksempel på en todimensjonal liste av tall som har et bestemt antall rader x og et bestemt antall kolonner y. Du kan tenke på en matrise som en liste med x antall elementer, hvor hvert element er en liste av størrelse y. I denne oppgaven skal vi se på matriseaddisjon. I denne oppgaven definerer vi addisjon av to matriser på samme måte som med vektoraddisjon: dersom vi skal summere matrise a med b og kaller den nye matrisen for c, vil *c[x][y]* være *a[x][y]* + *b[x][y]*, hvor *c[x][y]* er elementet i matrisen c som befinner seg på rad *x* og kolonne *y*.

Du får gitt en main-funksjon med følgende kode:

In [14]:
def main():
    A = random_matrix(4,3)
    print_matrix(A, 'A')
    B = random_matrix(3,4)
    print_matrix(B, 'B')
    C = random_matrix(3,4)
    print_matrix(C, 'C')
    D = matrix_addition(A,B)
    E = matrix_addition(B,C)
    print_matrix(E, 'B+C' )
    
main()

A = 
   6    3    4 
   0    8    8 
   6    0    1 
   4    5    2 

B = 
   5    7    5    1 
   4    2    1    1 
   3    4    8    2 

C = 
   7    6    8    0 
   8    2    5    0 
   5    4    0    4 

Matrices must have the same shape
B+C = 
  12   13   13    1 
  12    4    6    1 
   8    8    8    6 



som, etter at du har gjort oppgaven, skal gi følgende utskrift:

```python
A=[
   [1, 8, 4, 3]
   [5, 1, 5, 8]
   [9, 5, 8, 0]
  ]
B=[
   [7, 3, 3]
   [2, 1, 7]
   [2, 2, 3]
   [3, 5, 9]
  ]
C=[
   [4, 4, 6]
   [1, 9, 0]
   [9, 8, 5]
   [2, 9, 5]
  ]
Matrisene er ikke av samme dimensjon # A og B har ulike dimensjoner (ulikt antall rader og kolonner)
B+C=[
     [11, 7, 9]
     [3, 10, 7]
     [11, 10, 8]
     [5, 14, 14]
    ]
    ```
    

**Din oppgave**

Implementer funksjonene `random_matrise(bredde, høyde)`, `print_matrise(matrise, navn)` og `matrise_addisjon(a, b)` slik at utskriften av `main()` gir utskriften over. Du kan velge om du bruker vanlige lister eller numpy-arrays i denne oppgaven. Numpy-arrays har flere fordeler her, blant annet at man kan legge sammen to matriser med "+" og dette vil funke som det gjør i matte(slik utskriften over viser). Merk at dette ikke er tilfelle med vanlige lister så da må du selv itere gjennom listene og legge sammen tallene. Det er mange måter å løse oppgaven på. Hvis du trenger en "tom" array i numpy, kan en array med alle verdier lik 0 lages med [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html).

1. Funksjonen `random_matrise(bredde, høyde)` skal returnere en matrise med *høyde* antall rader og *bredde* antall kolonner. Matrisen skal være fylt med tilfeldige tall fra og med 0 til 10. Bruk random-biblioteket. 
2. `print_matrise(matrise, navn)` skal printe ut matrisene på samme format som vist i utskriften over. 
3. `matrise_addisjon(a, b)` skal ta inn to matriser og returnere en matrise som er summen av a og b. Dersom to matriser er av ulik størrelse er det umulig å addere matrisene og "Matrisene er ikke av samme dimensjon" skal skrives ut. 

***Skriv koden din i boksen under.***

In [13]:
import numpy as np

def random_matrix(m,n):
    matrix = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            matrix[i,j] = np.random.randint(0,9)
    return matrix

def print_matrix(matrix, name):
    print(f'{name} = ')
    for row in matrix:
        for element in row:
            print(f'{element:4.0f}', end=' ')
        print()
    print()
    
def matrix_addition(A,B):
    
    # Check if the matrices have the same shape
    if A.shape != B.shape:
        print('Matrices must have the same shape')
        return None
    
    m,n = A.shape
    C = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            C[i,j] = A[i,j] + B[i,j]
    return C





#### Hint

For å sjekke om to matriser er av samme dimensjon må du sjekke om de både har samme antall rader og samme antall kolonner. len(matrise) returnerer antall rader en matrise har, og len(matrise[0]) returnerer antall kolonner i matrisen. Dette funker også for numpy arrays. 